commitish: 'main'
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '⛓ Dependencies'
    labels:
      - 'dependencies'
      - 'deps'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's changed
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
autolabeler:
  - label: feature
    branch:
      - '/^feat(ure)?[/-].*/'
  - label: fix
    branch:
      - '/^fix[/-].*/'
  - label: chore
    files:
      - '*.md'
      - '*.yml'
    branch:
      - '/^docs?[/-].+/'
  - label: deps
    branch:
      - '/^dependabot\/.+/'
  - label: minor
    branch:
      - '/^feat(ure)?[/-].*/'
